version: "3"
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'test_rh'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./data/mysql/db:/var/lib/mysql