# Generated by Django 3.2.13 on 2022-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('hired_on', models.DateTimeField()),
                ('position', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('is_manager', models.BooleanField(default=False)),
                ('team', models.CharField(choices=[('DevOps_team', 'DevOps_team'), ('Dev_team', 'Dev_team'), ('Design_team', 'Design_team')], max_length=15)),
            ],
        ),
    ]
